
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgrzcynoqanewkvdjwzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJncnpjeW5vcWFuZXdrdmRqd3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTczODUsImV4cCI6MjA2MTA3MzM4NX0.Nu63vGOsNW9im0azlv-qeLWXg_ONeD8Jvo1xrAsE2ZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
